<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>ReqnrollAutomation</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.2.2" />
		<PackageReference Include="MSTest.TestFramework" Version="4.2.2" />
		<PackageReference Include="Reqnroll.MSTest" Version="3.3.4" />
		<PackageReference Include="Selenium.WebDriver" Version="4.43.0" />
		<PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="148.0.7778.9700" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Features\CarfaxCanada\" />
		<Folder Include="Hooks\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ReqnrollAutomation.Core\ReqnrollAutomation.Core.csproj" />
	</ItemGroup>

</Project>
