name: Reqnroll Automation

on:
  workflow_dispatch:
    inputs:
      execution_mode:
        description: "Execution Mode"
        required: true
        default: "parallel"
        type: choice
        options:
          - parallel
          - sequential
      category:
        description: "Category"
        required: false
        default: ""
        type: string
      test_environment:
        description: "Test Environment"
        required: true
        default: "QA"
        type: choice
        options:
          - QA
          - Dev
          - Prod

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      Headless: true
      TestEnvironment: ${{ inputs.test_environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore

      - name: Run Test
        run: |
          # If the user provided tags, add the filter flag; otherwise run everything
          if [ -n "${{ inputs.category }}" ]; then
            dotnet test --configuration Release --no-restore --settings ./${{ inputs.execution_mode }}.runsettings --filter "TestCategory=${{ inputs.category }}"
          else
            dotnet test --configuration Release --no-restore --settings ./${{ inputs.execution_mode }}.runsettings
          fi

      - name: Upload Test Results
        if: always() # Ensure this step runs even if the tests fail
        uses: actions/upload-artifact@v7
        with:
          name: TestReport
          path: '**/TestResults/ReqnrollAutomation/**/*'
          retention-days: 7
