name: Automation Test Suite

on:
  workflow_dispatch:
    inputs:
      run_mode:
        description: "Execution Mode"
        required: true
        default: "parallel"
        type: choice
        options:
          - parallel
          - sequential
      test_tags:
        description: "Category"
        required: false
        default: ""
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore

      - name: Run Test
        run: |
          # If the user provided tags, add the filter flag; otherwise run everything
          if [ -n "${{ inputs.test_tags }}" ]; then
            dotnet test --configuration Release --no-restore --settings ./${{ inputs.run_mode }}.runsettings --filter "TestCategory=${{ inputs.test_tags }}"
          else
            dotnet test --configuration Release --no-restore --settings ./${{ inputs.run_mode }}.runsettings
          fi

      - name: Upload Test Results
        if: always() # Ensure this step runs even if the tests fail
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: "TestResults/ReqnrollAutomation/**/Reports/"
          retention-days: 7