name: Reqnroll Automation

on:
  workflow_dispatch:
    inputs:
      target_project:
        description: "Target Project"
        required: true
        default: "CarfaxCanadaWebsite"
        type: choice
        options:
          - CarfaxCanadaWebsite
          - SwagLabs
      execution_mode:
        description: "Execution Mode"
        required: true
        default: "parallel"
        type: choice
        options:
          - parallel
          - sequential
      category:
        description: "Category"
        required: false
        default: ""
        type: string
      test_environment:
        description: "Test Environment"
        required: true
        default: "QA"
        type: choice
        options:
          - QA
          - Dev
          - Prod
  # Automatically trigger the workflow on push to the master branch
  push:
    branches:
      - master
    paths:
      - 'ReqnrollAutomation/**'

jobs:
  test:
    runs-on: windows-latest
    env:
      Headless: true
      TestEnvironment: ${{ inputs.test_environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      # Dynamically logs into personal NuGet feed using the stored secret
      - name: Authenticate NuGet Feed
        run: |
          dotnet nuget update source "khangvum-nuget" `
            --username "khangvum" `
            --password "${{ secrets.PAT_PACKAGE_READ_TOKEN }}" `
            --store-password-in-clear-text

      - name: Restore
        run: dotnet restore

      - name: Run Test
        run: |
          # Fallback to parallel execution if the input mode is blank
          EXECUTION_MODE="${{ inputs.execution_mode }}"
          EXECUTION_MODE="${EXECUTION_MODE:-parallel}"

          # Filter tests based on the selected target project if provided
          if [ -n "${{ inputs.target_project }}" ]; then
            FILTER_ARG="FullyQualifiedName~${{ inputs.target_project }}"
          fi

          # Append the category tag condition if provided
          if [ -n "${{ inputs.category }}" ]; then
            if [ -n "$FILTER_ARG" ]; then
              FILTER_ARG="${FILTER_ARG}&TestCategory=${{ inputs.category }}"
            else
              FILTER_ARG="TestCategory=${{ inputs.category }}"
            fi
          fi

          # Prepend the --filter flag prefix only if a filter string is constructed
          if [ -n "$FILTER_ARG" ]; then
            FILTER_ARG="--filter $FILTER_ARG"
          fi

          # Execute the target suite
          dotnet test \
            --configuration Release \
            --no-restore \
            --settings ./${EXECUTION_MODE}.runsettings \
            $FILTER_ARG

      - name: Upload Test Results
        if: always() # Ensure this step runs even if the tests fail
        uses: actions/upload-artifact@v7
        with:
          name: TestReport
          path: '**/TestResults/ReqnrollAutomation/**/*'
          retention-days: 7
 